### ISSUE TITLE
menuTitleColor will not change.

### ISSUE THREAD

**Issue by niebloomj** [PhamBaTho/BTNavigationDropdownMenu#23]

**Comment by niebloomj** [comment]
```self.menuTitleColor = ECUtilities.getColorForHex("#FEFEFE")```
does not actually change the color . The other setters work for the same get color method.

**Comment by xoyip** [comment]
I have the same problem in v0.2.1 .

**Comment by marcoscurvello** [comment]
anyone got a fix on this?

**Comment by osgafarov** [comment]
I also experience this issue.

**Comment by jakeatwork** [comment]
@niebloomj - i was having the same problem, tried a bunch of things and finally it turns out loading (in viewDidLoad):

    navigationController!.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName : UIColor.whiteColor()]

_before_ the menuView.menuTitleColor got it working.

I can't explain why right now, it's just late, but it seems it was an order of operations thing because initially I had the menuTitleColor set before navbar text attributes line. I moved it after and voila!

YMMV.

**Comment by PhamBaTho** [comment]
@niebloomj @pi-chan @marcoscurvello @osgafarov @jakeatwork I made in this release [0.3](https://github.com/PhamBaTho/BTNavigationDropdownMenu/releases/tag/0.3). 

Please feel free to reopen if you guys still experience this issue.
