### ISSUE TITLE
bounceOffset not available

### ISSUE THREAD

**Issue by trianglepixel** [PhamBaTho/BTNavigationDropdownMenu#50]
Unable to set bounceOffset in most recent version.

**Comment by PhamBaTho** [comment]
Yup, I removed bounceOffset as a property in recent versions. The reason is I didn't use contentOffset of tableView anymore, now I'm implementing dropdown menu animation with `usingSpringWithDamping: initialSpringVelocity`.
<img width="753" alt="screen shot 2016-04-18 at 1 05 01 pm" src="https://cloud.githubusercontent.com/assets/5548600/14595081/93a31e84-0566-11e6-8970-6488b96acc1b.png">
