### ISSUE TITLE
Last item on List still hidden with v0.4 update.

### ISSUE THREAD

**Issue by Sun3** [PhamBaTho/BTNavigationDropdownMenu#77]
Any update on the Rotation issue? I am still having this issue with v0.4. The last item in the list is not selectable. It is hidden below the bottom Toolbar or TabBar.

Thank you, great control love it.

**Comment by PhamBaTho** [comment]
@Sun3 Thanks for reminding me about Rotation issue when the list is long. About the last item is covered by Toolbar or TabBar, you can try to use `UIApplication.sharedApplication().keyWindow!` as `containerView`instead of `self.navigationController!.view`. In this way, the black overlay can cover the whole screen.
Please tell me more if it can solve your problem.

**Comment by Sun3** [comment]
@PhamBaTho Thanks for the suggestion. I tried it and works better but let's say I start the app in Portrait then rotate Landscape. Tap on the Downtown and me lost list last items are hidden.

**Comment by PhamBaTho** [comment]
@Sun3 yeah, I realized this issue yesterday so I created a new issue #78. Now I closed this issue to keep track of resolved issues. Feel free to re-open if it's still an issue for you.
